spring.application.name=E-Commerce-Back-End
# Server
server.port=8989

# MySQL Local
spring.datasource.url=jdbc:mysql://localhost:3306/afnandb
spring.datasource.username=root
spring.datasource.password=tumbin

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.web.resources.static-locations=file:uploads/
jwt.secret=mM2ZsRH9KwXJhvzFZxXryQvVZwHaIvXgnlP0SrXt8l8=

# =========================
# Spring Mail Configuration
# =========================
spring.mail.host=
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
